#!/bin/sh

set -e

chmod 755 /usr/lib/nautilus/extensions-2.0/python/nautilus-md5sum.py
cp /usr/share/nautilus-md5sum/nautilus-md5sum-notification /var/lib/update-notifier/user.d/
touch /var/lib/update-notifier/dpkg-run-stamp

#DEBHELPER#
