#!/bin/sh

set -e

#DEBHELPER#


dpkg-divert --package guada-ubiquity --remove /usr/lib/ubiquity/plugins/ubi-language.py
mv /usr/share/ubiquity/ubiquity-oldplugins/ubi-language.py.distrib  /usr/lib/ubiquity/plugins/

dpkg-divert --package guada-ubiquity --remove /usr/lib/ubiquity/plugins/ubi-timezone.py
mv /usr/share/ubiquity/ubiquity-oldplugins/ubi-timezone.py.distrib  /usr/lib/ubiquity/plugins/

dpkg-divert --package guada-ubiquity --remove /usr/lib/ubiquity/plugins/ubi-console-setup.py
mv /usr/share/ubiquity/ubiquity-oldplugins/ubi-console-setup.py.distrib  /usr/lib/ubiquity/plugins/
